<?php require_once './templates/layout/header.php'; ?>

<section class="">
    <form action="<?= BASE_URL ?>addBook" method="POST">
        <h3>Añadir Nuevo Libro</h3>

        <label for="titulo">Título </label>
        <input type="text" name="titulo" id="titulo" required>

        <label for="autor">Autor </label>
        <input type="text" name="autor" id="autor" required>

        <label for="genero">Género </label>
        <input type="text" name="genero" id="genero" required>

        <label for="precio">Precio</label>
        <input type="number" step="0.01" name="precio" id="precio" required>

        <label for="descripcion">Descripción</label>
        <input type="text" name="descripcion" id="descripcion" required>

        <label for="idEditorial">Editorial </label>
        <select name="idEditorial" id="idEditorial" required>
            <option value="" disabled selected>Seleccionar Editorial</option>
            <?php foreach ($editorials as $editorial): ?>
                <option value="<?= htmlspecialchars($editorial->ID_Editorial) ?>">
                    <?= htmlspecialchars($editorial->nombre) ?>
                </option>
            <?php endforeach; ?>
        </select>

        <button type="submit" class="btn btn-success mt-2">Aceptar</button>
    </form>
</section>

<?php require_once './templates/layout/footer.php'; ?>



