<?php require_once './templates/layout/header.php'?>

<h3>Editoriales con las que trabajamos</h3>
<div class="list-container">
    <table>
        <tr>
            <td>Nombre</td>
            <td>País</td>
            <td>Catalogo</td>
        </tr>
        <?php foreach($editorials as $editorial): ?> 
            <tr>
                <td> <?= htmlspecialchars($editorial->nombre) ?> </td>
                <td> <?= htmlspecialchars($editorial->pais) ?> </td>
    
                <td><a href="booksByEditorial/<?= htmlspecialchars($editorial->ID_Editorial) ?>">ver libros</a> </td> 
            </tr>
        <?php endforeach ?>
    </table>
</div>

<?php require_once './templates/layout/footer.php'?>
