<?php require_once './templates/layout/header.php'?>

<h3>Editoriales con las que trabajamos</h3>
<div class="list-container">
    <table>
        <tr>
            <td>Nombre</td>
            <td>País</td>
            <td>Acciones</td>
            <td>Visualizar</td>
        </tr>
        <?php foreach($editorials as $editorial): ?> 
            <tr>
                <td> <?= htmlspecialchars($editorial->nombre) ?> </td>
                <td> <?= htmlspecialchars($editorial->pais) ?> </td>
                <td>
                <?php if (isset($_SESSION['ID_USER'])): ?>
                    <form action="<?= BASE_URL ?>editEditorial/<?= htmlspecialchars($editorial->ID_Editorial) ?>" method="GET">
                        <button type="submit">Editar</button>
                    </form>
                    <form action="<?= BASE_URL ?>deleteEditorial" method="POST">
                        <input type="hidden" name="editorial_id" value="<?= htmlspecialchars($editorial->ID_Editorial) ?>">
                        <button type="submit">Eliminar</button>
                    </form>
                <?php endif; ?>
                </td>
                <td><a href="booksByEditorial/<?= htmlspecialchars($editorial->ID_Editorial) ?>">ver libros</a> </td>
            </tr>
        <?php endforeach ?>
    </table>
    <div>
        <a href="<?= BASE_URL ?>addEditorial">Agregar Nueva Editorial</a>
    </div>
</div>

<?php require_once './templates/layout/footer.php'?>
